---
# Set to the local folder you want shared to the VM. Note this directory must
# exist on the your machine before running Vagrant.
synced_folder: ~/Sites/www

# Adjust the Base Memory and CPUs provisioned for the VM.
memory: 1024
cpus: 2

# Define a list of sites with the following keys:
# - shortname: The site's shortname.
# - vhost: An associative array, containing:
#   - servername: The domain.
#   - documentroot: Path to the site docroot in the VM. If you're using the
#     synced_folder option, you only need to specify the path relative to
#     your synced folder. Otherwise, you need to specify the full path to
#     the docroot inside of the VM.
#
# Example:
sites:
- subscription: site1
  shortname: site1
  vhost:
    servername: local.site1.com
    documentroot: site1/docroot
- subscription: site2
  shortname: site2
  vhost:
    servername: local.site2.com
    documentroot: site2/docroot
- subscription: site2
  shortname: site2_demo
  vhost:
    servername: local.demo.site2.com
    documentroot: site2/docroot

# General config for enabling "add ons".
config:
  # Add New Relic integration. More info: https://docs.newrelic.com/docs/agents/php-agent/getting-started/new-relic-php
  # Remove newrelic config entirely to disable.
  newrelic:
    license: licensekey
    prefix: username
  nodejs: true
  phantomjs: true
  ruby: true
  splunk: true
  # Note that the mailcatcher role requires the ruby role.
  mailcatcher: true
