---
vagrant:
  # Set to the local folder you want shared to the VM:
  synced_folder: "~/Sites/www"
  ip: "172.17.17.17"

virtualbox:
  # Adjust the Base Memory provisioned for the VM:
  memory: "1024"
  # Allow port-forwarding to be set up here.
  # Ex: Forward port 80 to 8080.
  # port-forwarding:
  #   - name: http
  #     guest: 80
  #     host: 8080

ansible:
  # Define a list of sites with the following keys:
  #
  # shortname       = site's shortname
  # vhost           = assoc array with:
  #   servername    = domain name
  #   documentroot  = site docroot, relative to synced_folder
  #
  # Example:
  #  sites:
  #  - shortname: "site1"
  #    vhost:
  #      servername: "local.site1.com"
  #      documentroot: "site1/docroot"
  #  - shortname: "site2"
  #    vhost:
  #      servername: "local.site2.com"
  #      documentroot: "site2/docroot"
