---
- name: "install packages required to build ruby"
  apt: "pkg={{ item }} state=installed"
  with_items:
    - zlib1g-dev
    - libssl-dev

- name: "download ruby"
  get_url: >
    url={{ ruby_download_url }}
    dest={{ workspace }}/ruby-{{ ruby_version }}.tar

- name: "extract ruby"
  command: >
    tar -zxf {{ workspace }}/ruby-{{ ruby_version }}.tar
    chdir={{ workspace }}
    creates={{ workspace }}/ruby-{{ ruby_version }}

- name: "install libffi-dev"
  apt: name=libffi-dev state=present
  sudo: yes

- name: "build ruby"
  command: >
    {{ item }}
    chdir={{ workspace }}/ruby-{{ ruby_version }}
    creates=/usr/local/bin/ruby
  with_items:
    - ./configure
    - make
    - sudo make install

- name: "add ruby symlinks"
  file: >
    src=/usr/local/bin/{{ item }}
    dest=/usr/bin/{{ item }}
    state=link
    force=yes
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby
    - testrb

- name: "install ruby gems"
  gem: name={{ item }} state=present user_install=no
  with_items: ruby_gems
  sudo: yes
