---
- name: "clone drush from github"
  git: >
    repo=https://github.com/drush-ops/drush.git
    dest={{ drush_install_path }}
    version={{ drush_version }}
  tags: drush

- name: "install drush dependencies with composer"
  composer: >
    command=install
    working_dir={{ drush_install_path }}
  tags: drush

- name: "create drush symlink"
  file: src={{ drush_install_path }}/drush dest={{ drush_path }} state=link
  tags: drush

- name: "create drush6 symlink"
  file: src={{ drush_path }} dest={{ drush6_path }} state=link
  tags: drush

- name: "run drush to finish setting it up"
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
  tags: drush

- name: "copy drush file for bash alias and autocompletion"
  shell: cp {{ drush_install_path }}/examples/example.bashrc /home/vagrant/.drush_bashrc
  args:
    creates: /home/vagrant/.drush_bashrc
  tags: drush

- name: "include drush in bash profile"
  lineinfile:
    dest=/home/vagrant/.profile
    regexp="^.*drush_bashrc"
    line="if [ -f ~/.drush_bashrc ] ; then . ~/.drush_bashrc ; fi"
    state=present
  tags: drush

- name: "clone drush7 from github"
  git: >
    repo=https://github.com/drush-ops/drush.git
    dest={{ drush7_install_path }}
    version={{ drush7_version }}
  tags: drush

- name: "install drush7 dependencies with composer"
  composer: >
    command=install
    working_dir={{ drush7_install_path }}
  tags: drush

- name: "create drush7 symlink"
  file: src={{ drush7_install_path }}/drush dest={{ drush7_path }} state=link
  tags: drush
