---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
  - common
  - apache
  - php
  - php-mysql
  - php-pear
  - php-xdebug
  - php-xhprof
  - composer
  - drush
  handlers:
  - name: "restart webserver"
    service: name=apache2 state=restarted
  - name: "restart php-fpm"
    service: name=php5-fpm state=restarted
