---
- hosts: all
  sudo: yes
  roles:
  - common
  - apache
  - mysql
  - php
  - php-mysql
  - php-pear
  - php-xdebug
  - php-xhprof
  - composer
  - drush
  - memcached
  - nfs
  - drupal
  - splunk
  - mailcatcher
  handlers:
  - name: "restart webserver"
    service: name=apache2 state=restarted
  - name: restart mysql
    service: name=mysql state=restarted
  - name: "restart php-fpm"
    service: name=php5-fpm state=restarted
  - name: "restart memcached"
    service: name=memcached state=restarted
